version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0.7-2.1.105
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./src/payment.csproj && dotnet publish ./src/payment.csproj -c Release -o ./obj/Docker/publish"
